//Demonstrate check boxes.
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

class Main implements ItemListener {
	JLabel jlabSelected;
	JLabel jlabChanged;
	JCheckBox web;
	JCheckBox desktop;
	JCheckBox mobile;
	JPanel panel;
	JLabel top;

	Main() {
		// Create a new JFrame container.
		JFrame jfrm = new JFrame("JavaFX CheckBox to Swing CheckBox");
		// Specify FlowLayout for the layout manager.
		jfrm.setLayout(new GridBagLayout());
		// Give the frame an initial size.
		jfrm.setSize(240, 180);
		// Terminate the program when the user closes the application.
		jfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		
		panel = new JPanel();
		panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
		
		top = new JLabel("Select App Deployment Options");
		top.setAlignmentX(Component.CENTER_ALIGNMENT);
		
		// Create empty labels.
		jlabSelected = new JLabel("Nothing Clicked");
		jlabSelected.setAlignmentX(Component.CENTER_ALIGNMENT);
		jlabChanged = new JLabel("<none>");
		jlabChanged.setAlignmentX(Component.CENTER_ALIGNMENT);
		// Make check boxes.
		web = new JCheckBox("Web");
		web.setAlignmentX(Component.CENTER_ALIGNMENT);
		desktop = new JCheckBox("Desktop");
		desktop.setAlignmentX(Component.CENTER_ALIGNMENT);
		mobile = new JCheckBox("Mobile");
		mobile.setAlignmentX(Component.CENTER_ALIGNMENT);
		// Events generated by the check boxes
		// are handled in common by the itemStateChanged()
		// method implemented by Main.
		web.addItemListener(this);
		desktop.addItemListener(this);
		mobile.addItemListener(this);
		// Add check boxes and labels to the content pane.
		
		panel.add(top);
		panel.add(web);
		panel.add(desktop);
		panel.add(mobile);
		panel.add(jlabChanged);
		panel.add(jlabSelected);
		
		jfrm.add(panel, new GridBagConstraints());
		// Display the frame.
		jfrm.setVisible(true);
	}
	
	 // This is the handler for the check boxes.
    public void itemStateChanged(ItemEvent ie) {
        String str = "";
        // Obtain a reference to the check box that
        // caused the event.
        JCheckBox cb = (JCheckBox) ie.getItem();
        // Report what check box changed.
        if(cb.isSelected()) {
            jlabChanged.setText("Clicked: " + cb.getText());
        }
            
        if(web.isSelected()) {
            str += "Web ";
        }
        if(desktop.isSelected()) {
            str += "Desktop ";
        }
        if(mobile.isSelected()) {
            str += "Mobile";
        }
        jlabSelected.setText("Selected check boxes: " + str); 
    }


	public static void main(String args[]) {
	// Create the frame on the event dispatching thread.
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				new Main();
			}
		});
	}
}